routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/about', 'AboutController@index')->name('about');
Route::get('/home', 'HomeController@index');
Route::get('/productsales/{categoria}', 'ProductSalesController@getProductsbyCategory')->name('getProductsbyCategory'); 
Route::get('/products', 'ProductSalesController@getProductsbyName')->name('getProductsbyName'); 
Route::get('/productsalesdetails/{id}', 'ProductSalesController@getProductsDetails')->name('getProductsDetails');
Route::get('/showClient/{id}', 'ClientController@showClient')->name('showClient');
Route::get('/sale', 'ProductSalesController@sale')->name('sale'); 

Route::get('/salesClient/{id}', 'ProductSalesController@salesClient')->name('salesClient');
Route::get('/salesClient/show/{id}', 'ProductSalesController@showSalesClient')->name('showSalesClient');
Route::get('/undeliveredSales', 'ProductSalesController@undeliveredSales')->name('undeliveredSales'); 
Route::get('/unpaidSales', 'ProductSalesController@unpaidSales')->name('unpaidSales'); 

Route::post('/updateEntrega/{id}', 'ProductSalesController@updateEntrega')->name('updateEntrega'); 

Route::get('/client/{id}/edit', 'ClientController@edit')->name('editClient');
Route::get('/product/{id}/edit', 'ProductController@edit')->name('editProduct');
Route::get('/user/{id}/edit', 'UserController@edit')->name('editUser');

Route::post('/storeSale', 'ProductSalesController@storeSale')->name('storeSale'); 
Route::post('/updateImage', 'ProductController@updateImage')->name('updateImage'); 

Route::post('/product/promocao/{id}', 'ProductController@updatePromotion')->name('updatePromotion'); 

Route::post('/salesClient/savePayment', 'ProductSalesController@savePayment')->name('savePayment'); 
Route::post('/salesClient/saveDelivery', 'ProductSalesController@saveDelivery')->name('saveDelivery'); 

Route::resource('user','UserController');
Route::resource('product','ProductController');
Route::resource('client','ClientController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Product;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use File;
use JsValidator;
use Illuminate\Support\Facades\Validator;
class ProductController extends Controller
{

    public function __construct()
    {
        $this->middleware('acessoAdministrativo');
        $this->middleware('acessoVendedor',['except' => ['index']]);
        $this->middleware('auth');
    }

    protected $validationRules=[
        'nomeProduto' => 'required|max:255|unique:products,nomeProduto',
        'codProduto' => 'required|max:9999999999999999999|unique:products,codProduto',
        'qntEstoque' => 'required|integer|max:999999999999999999',
        'image' => 'required|image',
        'preco' => 'required|max:99999999',
        'categoria' => 'required',
        'composicao' => 'required|max:255|',
        'peso'=>'required',
        'valorCalorico'=>'required',
        'carboidratos'=>'required',
        'proteinas'=>'required',
        'gordurasT'=>'required',
        'gordurasS'=>'required',
        'colesterol'=>'required',
        'fibraAlimentar'=>'required',
        'calcio'=>'required',
        'ferro'=>'required',
        'sodio'=>'required',
    ];

    protected $messages = [
        'nomeProduto.required' => 'Você deve inserir um nome.',
        'nomeProduto.max' => 'Você deve inserir no máximo 255 caracteres',
        'nomeProduto.unique' => 'Nome não disponivel, insira outro',

        'qntEstoque.required' => 'Você deve inserir a quantidade em estoque.',
        'qntEstoque.integer' => 'Quantidade deve ser inteira.',
        'qntEstoque.max' => 'Você deve inserir no máximo 20 digitos',

        'image.required' => 'Você deve inserir uma imagem.',
        'image.Image' => 'Você deve inserir uma imagem.',

        'preco.required' => 'Você deve inserir o valor do produto.',
        'preco.max' => 'Você deve inserir no máximo 8 digitos',

        'codProduto.required' => 'Você deve inserir o código de barras do produto.',
        'codProduto.integer' => 'O código de barras é somente numeros.',
        'codProduto.unique' => 'Codigo de Barra ja cadastrado, insira outro',
        'codProduto.max' => 'Você deve inserir 13 dígitos',

        'categoria.required' => 'Você deve informar a categoria do produto.',

        'composicao.required' => 'Você deve informar a composição do produto',
        'composicao.max'=>'Você deve inserir no máximo 255 caracteres',
        'peso.required' => 'Você deve informar o peso do produto',
        'valorCalorico.required' => 'Você deve informar o valor calórico do produto',
        'carboidratos.required' => 'Você deve informar um valor para carboidratos do produto',
        'proteinas.required' => 'Você deve informar as proteínas do produto',
        'gordurasT.required' => 'Você deve informar as gorduras totais do produto',
        'gordurasS.required' => 'Você deve informar as gorduras saturadas do produto',
        'colesterol.required' => 'Você deve informar o valor de colesterol do produto',
        'fibraAlimentar.required' => 'Você deve informar a fibra alimentar do produto',
        'calcio.required' => 'Você deve informar o cálcio do produto',
        'ferro.required' => 'Você deve informar o valor de ferro do produto',
        'sodio.required' => 'Você deve informar o valor do sódio do produto',
    ];

    protected $categorias = [
        "Alimentos" => "Alimentos",
        "Doces - Salgados" => "Doces - Salgados",
        "Frutas - Verduras" => "Frutas - Verduras",
        "Higiene - Limpeza" => "Higiene - Limpeza",
        "Padaria" => "Padaria",
        "Frios" => "Frios",
        "Bebidas" => "Bebidas",
        "Itens diversos" => "Itens diversos",
    ];

    /**
     * Display a listing of the resource. 
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $nome = $request->input("nome");
        $products = Product::where('nomeProduto','LIKE',"%$nome%")->get();        
        return view('product/index',['products'=> $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $validator = JsValidator::make($this->validationRules, $this->messages);
        $product = new Product();
        return view('product/create',['product' => $product, 'categorias' => $this->categorias, 'validator' => $validator]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $categoria = $request->input('categoria');
        if($categoria == "Higiene - Limpeza" or $categoria == "Frutas - Verduras" or $categoria == "Itens diversos")
        {
            $this->validationRules["valorCalorico"] = "";
            $this->validationRules["gordurasT"] = "";
            $this->validationRules["proteinas"] = "";
            $this->validationRules["carboidratos"] = "";
            $this->validationRules["gordurasS"] = "";
            $this->validationRules["colesterol"] = "";
            $this->validationRules["calcio"] = "";
            $this->validationRules["fibraAlimentar"] = "";
            $this->validationRules["ferro"] = "";
            $this->validationRules["sodio"] = "";
        }
        $v = Validator::make($request->all(), $this->validationRules, $this->messages);
        
        if ($v->fails())
        {
            return redirect()->back()->withInput()->withErrors($v->errors());
        }

        
        $fileName = null;

        if ($request->hasFile('image')){
            $file = $request->file('image'); 
            $fileName =  time().'.'.$file-> getClientOriginalExtension();
            $fileName = str_replace(" ","",$fileName);
        }

        $product = new Product();
        $product->nomeProduto = $request-> input('nomeProduto');
        $product->qntEstoque = $request->input('qntEstoque');
        $product->imagem = $fileName;
        $product->categoria = $categoria;
        $product->tipoProduto = $request->input('tipoProduto');
        $product->preco = $request->input('preco');
        $product->codProduto = $request->input('codProduto');
        $product->unidadeProduto =  $request->input('unidadeProduto');
        $product->composicao =  $request->input('composicao');
        $product->peso =  $request->input('peso');
        $product->glutem =  $request->input('glutem');
        $product->lactose =  $request->input('lactose');
        $product->valorCalorico =  $request->input('valorCalorico');
        $product->carboidratos =  $request->input('carboidratos');
        $product->proteinas =  $request->input('proteinas');
        $product->gordurasT =  $request->input('gordurasT');
        $product->gordurasS =  $request->input('gordurasS');
        $product->colesterol =  $request->input('colesterol');
        $product->fibraAlimentar =  $request->input('fibraAlimentar');
        $product->calcio =  $request->input('calcio');
        $product->ferro =  $request->input('ferro');
        $product->sodio =  $request->input('sodio');
        $product->promocao = 0;
        $product->descontoPromocao = 0;
        
        if($product->save()){
            $destinationPath = 'storage/media/products';
            if ($fileName != null){
                $file->move($destinationPath,$fileName);    
            }
            return redirect()->route('product.index')->with('sucesso', 'Produto cadastrado com sucesso!');;
        } else{
            throw new \Exception("Houve um erro ao cadastrar o produto");
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);

        $validacaoNome = $this->validationRules["nomeProduto"];
        $validacaoNome = "$validacaoNome,$product->id";
        $this->validationRules["nomeProduto"] = $validacaoNome;

        $validacaoCodigo = $this->validationRules["codProduto"];
        $validacaoCodigo = "$validacaoCodigo,$product->id";
        $this->validationRules["codProduto"] = $validacaoCodigo;

        $this->validationRules["image"] = "";
        $validator = JsValidator::make($this->validationRules, $this->messages);
        
        
        return view('product.edit',['product' => $product, 'categorias' => $this->categorias, 'validator' => $validator]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);

        $validacaoNome = $this->validationRules["nomeProduto"];
        $validacaoNome = "$validacaoNome,$product->id";
        $this->validationRules["nomeProduto"] = $validacaoNome;

        $validacaoCodigo = $this->validationRules["codProduto"];
        $validacaoCodigo = "$validacaoCodigo,$product->id";
        $this->validationRules["codProduto"] = $validacaoCodigo;

        $this->validationRules["image"] = "";

        $categoria = $request->input('categoria');
        if($categoria == "Higiene - Limpeza" or $categoria == "Frutas - Verduras" or $categoria == "Itens diversos")
        {
            $this->validationRules["valorCalorico"] = "";
            $this->validationRules["gordurasT"] = "";
            $this->validationRules["proteinas"] = "";
            $this->validationRules["carboidratos"] = "";
            $this->validationRules["gordurasS"] = "";
            $this->validationRules["colesterol"] = "";
            $this->validationRules["calcio"] = "";
            $this->validationRules["fibraAlimentar"] = "";

resources/views/product/create.blade.php
@extends('layouts.template')
@section('content')
<link href="{{ asset('styles/indexProduto.css') }}" rel="stylesheet">

<div class="margemForm">
        <h2> <a href="{{route ('product.index')}}"><span class="ion-arrow-left-c"></span></a> Cadastro de produto</h2>
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-horizontal">
                    {{Form::model($product, array('route' => array('product.store'), 'id' => 'crud-form', 'files' => 'true'))}}

                    <div class="form-group">
                        {{Form::label('nome', 'Nome:',['class' => 'col-lg-3 control-label'])}}
                        {{Form::text('nomeProduto',null,['class' => 'col-lg-8 form'])}}
                        @if ($errors->has('nomeProduto'))
                            {{$errors->first('nomeProduto')}}
                        @endif 
                        
                    </div>

                <div class="form-group">
                    {{Form::label('qntEstoque', 'Quantidade em estoque:',['class' => 'col-lg-3 control-label'])}}
                    {{Form::text('qntEstoque',null,['class' => 'col-lg-8 form'])}}
                    @if ($errors->has('qntEstoque'))
                        {{$errors->first('qntEstoque')}}
                    @endif 
                </div>

                <div class="form-group">
                    {{Form::label('image', 'Imagem:',['class' => 'col-lg-3 control-label'])}}
                    {{Form::file('image',null,['class' => 'col-lg-8 form', 'accept' => 'image/*'])}}
                    @if ($errors->has('image'))
                        {{$errors->first('image')}}
                    @endif 
                </div>

                <div class="form-group">
                    {{Form::label('tipoProduto', 'Tipo Produto:',['class' => 'col-lg-3 control-label'])}}
                    {{Form::label('tipoProduto', 'Não Perecível:',['class' => 'col-lg-2 control-label'])}}
                    {{Form::radio('tipoProduto', 'Não Perecível', 'Não Perecível',['class' => 'col-lg-2 form']) }}
                    {{Form::label('tipoProduto', 'Perecível:',['class' => 'col-lg-2 control-label'])}}
                    {{Form::radio('tipoProduto', 'Perecível', 'Perecível',['class' => 'col-lg-2 form']) }}
                </div>

                <div class="form-group">
                    {{Form::label('preco', 'Preço:',['class' => 'col-lg-3 control-label'])}}
                    {{Form::text('preco',null,['class' => 'col-lg-8 form'])}}
                    @if ($errors->has('preco'))
                    {{$errors->first('preco')}}
                    @endif 
                </div>

                <div class="form-group">
                    {{Form::label('codProduto', 'Código de Barras:',['class' => 'col-lg-3 control-label'])}}
                    {{Form::text('codProduto',null,['class' => 'col-lg-8 form'])}}
                    @if ($errors->has('codProduto'))
                        {{$errors->first('decodProduto')}}
                    @endif 
                </div>

                <div class="form-group">
                    {{Form::label('unidadeProduto', 'Unidade do Produto:',['class' => 'col-lg-3 control-label'])}}
                    {{Form::label('unidadeProduto', 'Kg:',['class' => 'col-lg-2 control-label'])}}
                    {{Form::radio('unidadeProduto', 'kg', 'kg',['class' => 'col-lg-2 form']) }}
                    {{Form::label('unidadeProduto', 'Und:',['class' => 'col-lg-2 control-label'])}}
                    {{Form::radio('unidadeProduto', 'und', 'und',['class' => 'col-lg-2 form']) }}
                </div>

                <div class="form-group">
                    {{Form::label('categoria', 'Categoria:',['class' => 'col-lg-3 control-label'])}}
                    {{Form::select('categoria',$categorias,null,array('class' => 'form col-lg-8','id'=>'selectCategoria'))}}
                </div>

                <div class="form-group">
                    {{Form::label('composicao', 'Ingredientes/Composição:',['class' => 'col-lg-3 control-label'])}}
                    {{Form::text('composicao',null,['class' => 'col-lg-8 form'])}}
                </div>

                <div class="form-group">
                    {{Form::label('peso', 'Peso/quantidade:',['class' => 'col-lg-3 control-label'])}}
                    {{Form::text('peso',null,['class' => 'col-lg-8 form'])}}
                </div>  
            
                <div class="desabilitar">
                        <div class="form-group">
                            {{Form::label('glutem', 'Glútem:',['class' => 'col-lg-3 control-label'])}}
                            {{ Form::checkbox('glutem',1, null)}}
                        </div>

                        <div class="form-group">
                            {{Form::label('lactose', 'Lactose:',['class' => 'col-lg-3 control-label'])}}
                            {{ Form::checkbox('lactose',1, null) }}
                        </div>

                        <div class="form-group">
                            {{Form::label('valorCalorico', 'Valor Calórico:',['class' => 'col-lg-3 control-label'])}}
                            {{Form::text('valorCalorico',null,['class' => 'col-lg-8 form'])}}
                        </div>

                        <div class="form-group">
                            {{Form::label('carboidratos', 'Carboidratos:',['class' => 'col-lg-3 control-label'])}}
                            {{Form::text('carboidratos',null,['class' => 'col-lg-8 form'])}}
                        </div>

                        <div class="form-group">
                            {{Form::label('proteinas', 'Proteínas:',['class' => 'col-lg-3 control-label'])}}
                            {{Form::text('proteinas',null,['class' => 'col-lg-8 form'])}}
                        </div>

                        <div class="form-group">
                            {{Form::label('gordurasT', 'Gorduras Totais:',['class' => 'col-lg-3 control-label'])}}
                            {{Form::text('gordurasT',null,['class' => 'col-lg-8 form'])}}
                        </div>

                        <div class="form-group">
                            {{Form::label('gordurasS', 'Gorduras Saturadas:',['class' => 'col-lg-3 control-label'])}}
                            {{Form::text('gordurasS',null,['class' => 'col-lg-8 form'])}}
                        </div>

                        <div class="form-group">
                            {{Form::label('colesterol', 'Colesterol:',['class' => 'col-lg-3 control-label'])}}
                            {{Form::text('colesterol',null,['class' => 'col-lg-8 form'])}}
                        </div>

                        <div class="form-group">
                            {{Form::label('fibraAliementar', 'Fibra Alimentar:',['class' => 'col-lg-3 control-label'])}}
                            {{Form::text('fibraAlimentar',null,['class' => 'col-lg-8 form'])}}
                        </div>

                        <div class="form-group">
                            {{Form::label('calcio', 'Cálcio: ',['class' => 'col-lg-3 control-label'])}}
                            {{Form::text('calcio',null,['class' => 'col-lg-8 form'])}}
                        </div>

                        <div class="form-group">
                            {{Form::label('ferro', 'Ferro:',['class' => 'col-lg-3 control-label'])}}
                            {{Form::text('ferro',null,['class' => 'col-lg-8 form'])}}
                        </div>

                        <div class="form-group">
                            {{Form::label('sodio', 'Sódio:',['class' => 'col-lg-3 control-label'])}}
                            {{Form::text('sodio',null,['class' => 'col-lg-8 form'])}}
                        </div>
                    </div>
                    
                
                    <div class="form-group">
                        {{Form::reset('Limpar', array('class' => 'btn btn-danger limpar'))}}
                        {{Form::submit('Salvar', array('class' => 'btn btn-success salvar', 'id' => 'validar'))}}
                        {{Form::close()}}
                    </div>
                </div>
            </div>
        </div>
@endsection

@section('script')
    <script type="text/javascript" src="{{ asset('vendor/jsvalidation/js/jsvalidation.js')}}"></script>
    <script type="text/javascript" src="{{ asset('scripts/product.js')}}"></script>
    {!! $validator->selector('#crud-form') !!}
@endsection

resources/views/product/index.blade.php
@extends('layouts.template')
@section('content')


<link href="{{ asset('styles/indexProduto.css') }}" rel="stylesheet">
<link href="{{ asset('styles/campoPesquisa.css') }}" rel="stylesheet">


@if (session('sucesso'))
    <div class="ion-checkmark-circled alert alert-success">
        {{ session('sucesso') }}
    </div>
@endif

@if (session('erro'))
<div class="ion-alert-circled alert alert-danger">
    {{ session('erro') }}
</div>
@endif

<div class="margem">
  <div class="form-group">
      <a href= "{{ route('product.create') }}" class ="btn btn-danger">
          Cadastrar Novo Produto
      </a>
  </div>
  <hr/>
  <div class="row pesquisa">
    {{Form::open(array('route' => array('product.index'), 'method' => 'GET'))}}
      {{Form::label('nome', 'Nome do produto:',['class' => 'col-lg-2 control-label', 'style' => 'margin-left:8%;'])}}
      {{Form::text('nome',"",['class' => 'col-lg-7', 'style' => 'border-radius:4px; width: 50%;'])}}
      {{Form::submit('Consultar', array('class' => 'btn btn-danger pull-left col-lg-1' ,'style' => 'margin-top:-5px; margin-left:2%'))}}
    {{ Form::close() }}
  </div>
  <hr/>
  <h2 class="titulo">Lista de Produtos</h2>  
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Imagem</th>
        @if(Auth::user()->role != 'vendedor')
        <th>Editar imagem</th>
        @endif
        <th>Quantidade</th>
        <th>Categoria</th>
        <th>Valor</th>
        <th>Promoção</th>
        @if(Auth::user()->role != 'vendedor')
          <th>Editar</th>
          <th>Remover</th>
        @endif
      </tr>
    </thead>
    <tbody>
      @foreach($products as $product)
        <tr>
          <td><a href="{{route('getProductsDetails',$product->id)}}">{{$product->nomeProduto}}<a></td>
          <td>
            <div class="pull-left">
              <a href="{{route('getProductsDetails',$product->id)}}">
                <img src="{{ asset('storage/media/products/'.$product->imagem) }}" height="80" width="80">
              </a>
            </div>
          </td>
          @if(Auth::user()->role != 'vendedor')
            <td>
              <a class="btn btn-success uploadImage" id="{{$product->id}}">Trocar imagem</a>
              <div style="display:none">
                {{Form::open(array('route' => array('updateImage'), 'files' => 'true'))}}
                {{Form::text('id',$product->id,['style' => 'display:none'])}}
                {{Form::file('image',['accept' => 'image/*', 'id' => 'file-'.$product->id, 'onchange' => 'javascript:this.form.submit();'])}}
                {{Form::close()}}
              </div>
            </td>
          @endif
          <td>{{$product->qntEstoque.' '.$product->unidadeProduto}}</td>
          <td>{{$product->categoria}}</td>
          <td> 
            @if($product->promocao == 0)
              <br>
              {{'R$ '.number_format($product->preco, 2, ',', '.') }}
            @elseif ($product->promocao == 1)
              <div class="tachado">
                {{'R$ '.number_format($product->preco, 2, ',', '.') }}
              </div>
              {{'R$ '.number_format(($product->preco*(100-$product->descontoPromocao)/100), 2, ',', '.') }}
            @endif
          </td>

          <td> 
            <a data-toggle="modal" href='#promocao-{{$product->id}}'><button type="button" class="btn btn-danger ion-cash buttonIndex" ></button></a>
            <div class="modal fade" id="promocao-{{$product->id}}" role="dialog">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <h4 class="modal-title" id="myModalLabel">Cadastrar Promoção</h4>
                  </div>
                  <div class="modal-body">
                      <div class="form-horizontal ">
                          {{Form::model($product, array('route' => array('updatePromotion',$product->id)))}}
                          <div class="form-group">
                            {{Form::label('promo', 'Promoção:')}}
                            {{Form::checkbox('promocao',1, null)}}
                          </div>
                          <div class="form-group">
                            {{Form::label('porcent', 'Porcentagem(%):')}}
                            {{Form::text('descontoPromocao',null)}}
                          </div>
                          <div class="form-group">
                          </div>
                      </div>
                  </div>
                  <div class="modal-footer">
                      {{Form::submit('Salvar', array('class' => 'btn btn-success'))}}
                      <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                      {{Form::close()}}
                  </div>
                </div>
              </div>
            </div>
          </td>
          @if(Auth::user()->role != 'vendedor')
            <td><a href= "{{route('editProduct',$product->id)}}"> <button type="button" class="btn btn-danger ion-edit buttonIndex"></button></a></td>
            <td>
              {{ Form::open(array('url' => 'product/' . $product->id, 'class' => 'pull-left')) }}
                {{ Form::hidden('_method', 'DELETE') }}
                {{ Form::button('', array('type' => 'submit', 'class' => 'btn btn-danger ion-ios-trash buttonIndex')) }}
              {{ Form::close() }}
            </td>
          @endif
        </tr>
      @endforeach
    </tbody>
  </table>
</div>

@endsection

@section('script')
    <script type="text/javascript">
        setTimeout(function () {
            $('.alert-success').hide();
        }, 5000);

        setTimeout(function () {
            $('.alert-danger').hide();
        }, 5000);

        $(".uploadImage").click(function(){
          $("#file-"+this.id).click();
        });
    </script>
@endsection